### ISSUE TITLE
Can support Chia's k32

### ISSUE THREAD

**Issue by hitpp** [madMAx43v3r/mmx-node#1]
Can support Chia's k32, If you support it, you can directly bring a lot of space

**Comment by jinjiang2050** [comment]
If support Chives, it is also a good idea!

**Comment by madMAx43v3r** [comment]
No sorry, it would destroy the economic feedback loop to stabilize the price later on.

**Comment by gitrid** [comment]
Given the requirement to use "-x 11337" I understand that it also doesn't support chives plots?
BTW, your project is starting to get noticed by forks community, it would be great to expand readme section or you will be flooded with similar questions :-)

**Comment by onegoku** [comment]
> No sorry, it would destroy the economic feedback loop to stabilize the price later on.

Definitely right decision

**Comment by w0lv3r1nix** [comment]
Hey Max,

Which K should we use? K30?

**Comment by madMAx43v3r** [comment]
Which ever you like, for testnet K26 and up. If you want to be compatible with mainnet later, K30 or higher.

**Comment by prodchia** [comment]
"No sorry, it would destroy the economic feedback loop to stabilize the price later on."

Can you please elaborate ? thx

**Comment by madMAx43v3r** [comment]
Netspace is used to "vote" how many coins are created and how fast. If farming is free there will be a lot of coins with no value created.

**Comment by cjjxghbg** [comment]
> 不抱歉，它会破坏经济反馈循环以稳定价格。
You are the best, can it run on Windows?

**Comment by cjjxghbg** [comment]
You are the best, can it run on Windows?

**Comment by olegin77** [comment]
If you need any help or support community , marketing or smth else in Russian internet ,I have team, we can help you , or even smth else .and question about rewards in testnet , is that testnet with rewards in mainnet ? Or just testing and prep airing for mainnet?

**Comment by madMAx43v3r** [comment]
just testing, no coins will be transfered.

**Comment by madMAx43v3r** [comment]
> You are the best, can it run on Windows?

working on it

**Comment by programkom** [comment]
When will mainnet be started? Currently i'm running on testnet and from your response I assume that coins that are farmed on testnet will not be transfered/usefull on mainnet? So when mainnet is launched i start from scratch. this means i need to generate new wallet also?

**Comment by madMAx43v3r** [comment]
~6 months, yes to all.

**Comment by marinasflorin** [comment]
So right now, there's no point to farming this? If it isn't useful when the main net is launching?

**Comment by madMAx43v3r** [comment]
It's a testnet

**Comment by jnak** [comment]
> Netspace is used to "vote" how many coins are created and how fast. If farming is free there will be a lot of coins with no value created.

I love the idea of increasing the transaction speed of Chia but I respectfully disagree with this statement. In my view, being able to share plots with other currencies will allow all those currencies to benefit from increased security while allowing currencies to minimize coin creation (to reward farmers), hence limiting inflation and pushing coin prices up (assuming that's what you are interested in). I think that's a really incredible property of the Chia plotting model that will open the door to having layer 2 chains being as secure as layer 1 chains. For example, you could imagine your chain becoming the main Layer 2 to provide instant transaction to all the (future) currencies using Proof of Space.

**Comment by sengexyz** [comment]
Although I have more than 10k Chia k32 plots, I wish MMX can use the unique plot format. Looking at all Chia forks that share the Chia plots, none of them is succeeded in economy and ecosystem. MMX-node has the potential to be a great project, I hope the developer(s) can keep the momentum and make something real on the mainnet soon. As far as I know, most Chia farmers have lost their investment to some extent, the farmed XCH coins cannot cover the hardware cost, no mention of the time and efforts made in the farming process. MMX could be a saver for these farmers, the tons of HDDs have a chance to be more profitable. I might develop an easy-to-use GUI for MMX if this project goes well. I love Chia, MMX, and the people who created and developed these game-changer blockchains. Both projects are very friendly at licensing and open to the world. I also highly respect the developer(s) who is/are working on a huge project with an unforeseeable future.

**Comment by jnak** [comment]
Interesting. Could you elaborate why you think other PoS chains failed as a result of sharing their plotting format? 

I haven't looked at all the chia forks but the few I did look into didn't have much differentiators (that could lead to long term value and adoption) other than getting rid of the pre-farm. (Ironically, by getting rid of the pre-farm they prevent themselves from being able to invest the time and money necessary to make their project successful but I digress.) If you're concerned about being able to recoup your farming investment, I think you are far more likely to do it by being able to farm multiple currencies at the same time (vs betting on only one). The more people farm a PoS coin, the more secure it is, the more long term value the project has, the more likely your farming rewards will allow you to recoup your investment.

**Comment by programkom** [comment]
> ~6 months, yes to all.

but if i create new wallet for mainnet (when lauched), this means that new pool and farmer key will be issued and i need to re-generate plots that i made currently for testnet?

**Comment by madMAx43v3r** [comment]
> > ~6 months, yes to all.
> 
> but if i create new wallet for mainnet (when lauched), this means that new pool and farmer key will be issued and i need to re-generate plots that i made currently for testnet?

good point, if the key generation scheme changes yes...

**Comment by madMAx43v3r** [comment]
> > > ~6 months, yes to all.
> > 
> > 
> > but if i create new wallet for mainnet (when lauched), this means that new pool and farmer key will be issued and i need to re-generate plots that i made currently for testnet?
> 
> good point, if the key generation scheme changes yes...

Wait no, the BLS wallet is separate from the normal wallet, you just need the same seed value as you have now, see `mmx wallet get seed`.

**Comment by madMAx43v3r** [comment]
> Interesting. Could you elaborate why you think other PoS chains failed as a result of sharing their plotting format?

It's really simple, if farming is free the value of the coin will be close to zero.

**Comment by mr-bre** [comment]
> > > > ~6 months, yes to all.
> > > 
> > > 
> > > but if i create new wallet for mainnet (when lauched), this means that new pool and farmer key will be issued and i need to re-generate plots that i made currently for testnet?
> > 
> > 
> > good point, if the key generation scheme changes yes...
> 
> Wait no, the BLS wallet is separate from the normal wallet, you just need the same seed value as you have now, see `mmx wallet get seed`.

In practice, does that mean that when mainnet launch and i want to reuse plots that i have to generate a wallet on mainnet with the seed from my testnet wallet?
```
testnet: mmx wallet get seed
mainnet: mmx wallet create <seed>
```

"The minimum K size for mainnet will probably be k30, for testnets it is k26. The plots from testnets can be reused for mainnet later." -- README.md

**Comment by marinasflorin** [comment]
Does that mean that plotting now will be worth it for when the mainnet is launched because we'll have plots ready to be farmed?

**Comment by programkom** [comment]
> Does that mean that plotting now will be worth it for when the mainnet is launched because we'll have plots ready to be farmed?

i would say so, if and only if mr-bre's comment holds/is valid

**Comment by marinasflorin** [comment]
> 

Can you confirm if the plots we farm now can be reused when the mainnet launches?

**Comment by Ealrann** [comment]
@marinasflorin 
> The plots from testnets can be reused for mainnet later

As the Readme.md says: 
```The plots from testnets can be reused for mainnet later```

**Comment by jnak** [comment]
> It's really simple, if farming is free the value of the coin will be close to zero.

I don't think it's as simple as you suggest it is. In an efficient marketplace, price is entirely determined by demand and supply. In crypto, there are many factors that impact demand and supply.

Demand is determined by immediate value (ie I need this coin to do a transaction or execute a smart contract) and expected long-term value (ie I think this coin will increase in value because this chain is going to become the winner for green instant transactions and therefore a lot of people will need the coin to transact, or sadly because other people will also speculate its value will increase). One thing to note here is that the more decentralized your chain, the more secure it is, the more short term and long term value it has, the more demand, the more its price will increase.

Supply is entirely determined by the farming reward policy that you are designing. It has nothing to do with how expensive or cheap it is to farm. 

Interestingly, because the incremental cost of farming another crypto off the same chia plot is close to zero (though not free due to setup and maintenance cost), you could design a reward system that comparatively rewards a lot more transactions than empty block creation. This way you are guaranteeing the supply will grow alongside the demand of the chain. Given there are also a bit of setup costs for farmers, you could also decide that that the first year rewards are going to be much more than the following years. This way you give an incentive to farmers to bootstrap the network at the beginning when the long term success of the chain is still very unlikely (and hence making your network secure right off the bat).

This is a reward strategy that has never been available to PoW or PoS because they had to incentivize miners over time to spend a lot of money on mining equipment and electricity. I would really encourage to give it more thought.

One last thing to ponder is that if I were to maintain a fork of your chain with exactly the same thing, except for the farming reward system I just outlined, I'm confident that my chain would be more successful from a usage and coin value perspective. Why would anyone choose to transact on your chain, when mine is more secure and less inflationary than yours?

**Comment by madMAx43v3r** [comment]
It think you put too much emphasis on the security aspect, just because you have 10x more netspace / security doesn't make it 10x more usable or popular.

Also the value of your coin will be completely free-floating, since farming is (basically) fee and supply fixed, making it unusable as a currency.

**Comment by jnak** [comment]
> It think you put too much emphasis on the security aspect, just because you have 10x more netspace / security doesn't make it 10x more usable or popular.

I agree that 10x more nodes does not make the chain 10x more secure. In other words, I agree that there is no 1x linear correlation between security of the network and its size. However, there is definitely a positive correlation between the size of the network and its security. The more nodes always entails stronger security, which increases the popularity of the chain.

> Also the value of your coin will be completely free-floating, since farming is (basically) fee and supply fixed, making it unusable as a currency.

I didn't suggest the supply should be fixed. Actually quite the contrary - I recommended to make the supply increase as the actual volume of transactions increases. Also, the fact that a coin is expensive or cheap to farm is unrelated to the concept of free floating currencies. The only way to prevent a currency from being free floating is by actively managing its price using all sort of monetary mechanisms (usually using a treasury, collaterals or guarantees). See [this webpage](https://www.investopedia.com/terms/f/floatingexchangerate.asp) that explains well the concept.


Also, I completely forgot to include one key factor affecting the supply
of coins to be sold. If you don't allow plots to be shared with other PoS coins, then your farmers will expect to generate the entirety of their return on farming investment by selling your coin over time. If on the contrary, they can farm other PoS coins with the same plots, they will be able to amortize the same fixed investment cost over multiple chains, which will allow them to sell less of each coin in the short term. It's very common for farmers (or miners) to sell every so often a proceed of their earnings to slowly recoup their investments. If they can make the same amount of money by selling a bunch of different coins, they will have less incentive to sell a given coin in the short term and more incentive to hold onto a larger share of your coin, thus decreasing the supply of your coins to be sold and pushing up the price of the coins.

**Comment by prodchia** [comment]
I agree with @jnak to a large extent. The value of ETH is not driven by the cost of mining, but it's the market price of ETH that dictates the total hash rate. Chives are using unique plots, and that hasn't helped it's price.

**Comment by wsyang24** [comment]
I just like to add small opinions. If you take a look at blockchain project called Lumerin(https://lumerin.io/), it my help you design different blockchain rather than just another blockchain with higher performances. 

As far as I know there are too many blockchains which claims higher TPS than Ethereum, Polygon and Solana.

**Comment by madMAx43v3r** [comment]
> As far as I know there are too many blockchains which claims higher TPS than Ethereum, Polygon and Solana.

Correct, and all of them are based on Proof of Stake. MMX is not.

**Comment by madMAx43v3r** [comment]
> > It think you put too much emphasis on the security aspect, just because you have 10x more netspace / security doesn't make it 10x more usable or popular.
> 
> I agree that 10x more nodes does not make the chain 10x more secure. In other words, I agree that there is no 1x linear correlation between security of the network and its size. However, there is definitely a positive correlation between the size of the network and its security. The more nodes always entails stronger security, which increases the popularity of the chain.
> 
> > Also the value of your coin will be completely free-floating, since farming is (basically) fee and supply fixed, making it unusable as a currency.
> 
> I didn't suggest the supply should be fixed. Actually quite the contrary - I recommended to make the supply increase as the actual volume of transactions increases. Also, the fact that a coin is expensive or cheap to farm is unrelated to the concept of free floating currencies. The only way to prevent a currency from being free floating is by actively managing its price using all sort of monetary mechanisms (usually using a treasury, collaterals or guarantees). See [this webpage](https://www.investopedia.com/terms/f/floatingexchangerate.asp) that explains well the concept.
> 
> Also, I completely forgot to include one key factor affecting the supply of coins in the short and medium term. If you don't allow plots to be shared with other PoS coins, then your farmers will expect to generate the entirety of their return on farming investment by selling your coin over time. If on the contrary, they can farm other PoS coins with the same plots, they will be able to amortize the same fixed investment cost over multiple chains, which will allow them to sell less of each coin in the short and medium term. It's very common for farmers (or miners) to sell every so often a proceed of their earnings to slowly recoup their investments. If they can make the same amount of money by selling a bunch of different coins, they will have more financial freedom to sell less of each coin in the short and medium term, thus decreasing the available supply of coins in the market, hence pushing up the price of the coins (at least in the short and medium term).

1. The entire point of farming is to sell the coins. If you wanted to invest, you'd buy the coins.
2. Take a look at XFX or HDD, especially the ratio of netspace to coin price, and how it evolved over time. Hint: it dropped by ~100x, if farmers can make extra profit, they will sell, no matter if farming was free or not.

**Comment by Drhicom** [comment]
Is it time to close this issue to help clean up?
