### ISSUE TITLE
Wallet Get Seed

### ISSUE THREAD

**Issue by SametBasturkk** [madMAx43v3r/mmx-node#10]
xxxxx:~/Downloads/mmx-node/build$ ./mmx wallet keys
[mmx] ERROR: Failed to open wallet: vnx.NoSuchService

I cant get seeds from wallet snyc works great. 

How can I solve this problem?
and when mainnet?

**Comment by xkredr** [comment]
did you `mmx wallet create [-f filename]` first?
The filename is optional.

**Comment by SametBasturkk** [comment]
> did you `mmx wallet create [-f filename]` first? The filename is optional.

yes I did

**Comment by madMAx43v3r** [comment]
node needs to be running

**Comment by hlmlk** [comment]
just copy wallet.dat from build dir to mmx-node dir

**Comment by SametBasturkk** [comment]
> node needs to be running

node already running 

> just copy wallet.dat from build dir to mmx-node dir

already copied but same error

**Comment by SametBasturkk** [comment]
fixed. looks like restart solved
