### ISSUE TITLE
Check for duplicate plots

### ISSUE THREAD

**Issue by Drhicom** [madMAx43v3r/mmx-node#101]
Currently duplicate check is not there. I created a folder on a spare disk (dupe) and added it  in the harvester tab. Shut down MMX and copied 5 plots from a drive to the folder named dupe. deleted the log file so a new one would be made. Let it run for 10 minutes and nothing in the log file.

**Comment by madMAx43v3r** [comment]
Yes, it's a TODO.

**Comment by Drhicom** [comment]
Did I understand from the thread that you might have had a chance to do some of the TODO, when it finds a dupe plot is it possibly to display both locations to track them down?

**Comment by madMAx43v3r** [comment]
yeah both are displayed now

**Comment by Drhicom** [comment]
Will that be in the V0.8.7?

**Comment by Drhicom** [comment]
Jacek gave me the link to the new spot installed and dupe show up and display both locations.

Great work again Mr.

**Comment by Jacek-ghub** [comment]
@madMAx43v3r Could you add to your TODO list somewhere at the bottom a cross harvester check for dups?  I guess, we all from time to time get tired, and make mistakes when moving those plots around.  This issue is potentially hitting the newcomers the most.

I think that yesterday was a good example of a day when people start talking about plots, and the first thing they do is blame on the latest update.  I tried to get more info from those with problems, but it was difficult to get needed reply.  The more feedback harvester / farmer can provide, the easier it will be to help those people (less guessing).

**Comment by madMAx43v3r** [comment]
Yeah it's a bit more work to do across harvesters, gonna have to send a list of plots to the farmer and have the farmer check it.

**Comment by Jacek-ghub** [comment]
That is what I was thinking that needs to be done, so asked to push it down to the bottom of the TODO list.  It is for sure no rush to have it as it is not critical at all but would be a nice feature to have at some point later on.

**Comment by Drhicom** [comment]
Thanks you again sirs

**Comment by Jacek-ghub** [comment]
By the way, that host name addition to harvester lines is a game changer (for me, at least).  Really thank you for adding that. 
 Here is my output from the main node about those challenges (one hour snapshot):

> Harvester challenges:
> -- host: mule
> ---- challenges:
> ------ processed: 279, eligible: 216, avg eligible per challenge: 0.77
> ------ filter ratio: 600 : 1
> ------ eligible processing: avg: 0.18, min: 0.01, max: 0.61
> ------ best score: avg: 5489688, min: 66397, max: 16514610
> -- host: yak
> ---- challenges:
> ------ processed: 279, eligible: 216, avg eligible per challenge: 0.77
> ------ filter ratio: 559 : 1
> ------ eligible processing: avg: 0.24, min: 0.00, max: 0.91
> ------ best score: avg: 5073521, min: 36608, max: 16540420
> -- host: llama
> ---- challenges:
> ------ processed: 279, eligible: 274, avg eligible per challenge: 0.98
> ------ filter ratio: 519 : 1
> ------ eligible processing: avg: 0.23, min: 0.01, max: 0.86
> ------ best score: avg: 2750091, min: 1313, max: 16070486
