### ISSUE TITLE
Log analysis

### ISSUE THREAD

**Issue by Kerby247** [madMAx43v3r/mmx-node#11]
[Router] INFO: Connected to peer 222.93.112.226
[Router] WARN: send() failed with: Broken pipe (32)
[Router] INFO: Peer 76.31.27.210 disconnected
[Node] INFO: Verified VDF at 1173194940000 iterations, delta = 9.96527 sec, took 3.88272 sec
[Node] INFO: Committed height 47127 with: ntx = 0, score = 35, k = 30, tdiff = 34791, sdiff = 19503, bytes = 1101
[Node] INFO: New peak at height 47145 with score 240
[Harvester] INFO: 19 plots were eligible for height 47148, best score was 8610, took 1.96095 sec
[Node] INFO: Verified VDF at 1173229742000 iterations, delta = 10.0067 sec, took 3.59251 sec
[Node] INFO: Committed height 47128 with: ntx = 0, score = 196, k = 30, tdiff = 34799, sdiff = 19493, bytes = 1101
[Node] INFO: New peak at height 47146 with score 572
[Node] INFO: Created block at height 47146 with: ntx = 0, score = 413, reward = 0.441858 MMX, nominal = 0.441858 MMX, fees = 0 MMX
[Node] INFO: New peak at height 47146 with score 413 (forked at 47145)
[Router] INFO: Broadcasting block 47146
[Harvester] INFO: 12 plots were eligible for height 47149, best score was 11855, took 2.17035 sec
[Node] INFO: New peak at height 47146 with score 225 (forked at 47145)
[Router] WARN: Connecting to peer 73.51.246.177 failed with: connect() failed with: Resource temporarily unavailable (11)
[Router] WARN: Connecting to peer 10.0.0.138 failed with: connect() failed with: Resource temporarily unavailable (11)
[Router] WARN: Connecting to peer 23.243.218.10 failed with: connect() failed with: Resource temporarily unavailable (11)
[Router] WARN: Connecting to peer 81.174.156.111 failed with: connect() failed with: Resource temporarily unavailable (11)
[Router] WARN: Connecting to peer 1.64.102.203 failed with: connect() failed with: Resource temporarily unavailable (11)
[Router] WARN: Connecting to peer 140.250.81.233 failed with: connect() failed with: Resource temporarily unavailable (11)
[Router] WARN: Connecting to peer 77.185.205.192 failed with: connect() failed with: Resource temporarily unavailable (11)
[Router] WARN: Connecting to peer 159.48.55.97 failed with: connect() failed with: Resource temporarily unavailable (11)
[Router] WARN: Connecting to peer 47.243.30.161 failed with: connect() failed with: Resource temporarily unavailable (11)
[Router] WARN: Connecting to peer 76.120.155.174 failed with: connect() failed with: Resource temporarily unavailable (11)
[Router] INFO: Connected to peer 213.173.32.158
[Router] INFO: Peer 213.173.32.158 disconnected
[Node] INFO: Verified VDF at 1173264544000 iterations, delta = 10.0187 sec, took 3.60269 sec
[Node] INFO: Committed height 47129 with: ntx = 0, score = 131, k = 30, tdiff = 34819, sdiff = 19492, bytes = 1101
[Node] INFO: New peak at height 47147 with score 224

I use Google translate...
Glad to see you as a cryptocurrency developer.
Could you clarify some points in the work. Above is the progress log.

1. **[Router] WARN: send() failed with: Broken pipe (32)** - Worry about this?
2. **[Node] INFO: Verified VDF at 1173194940000 iterations, delta = 9.96527 sec, took 3.88272 sec** - Did the time took ok?
3. **[Router] WARN: Connecting to peer 73.51.246.177 failed with: connect() failed with: Resource temporarily unavailable (11)** - Are many lines like this normal?
4. **[Node] INFO: Created block at height 47146 with: ntx = 0, score = 413, reward = 0.441858 MMX, nominal = 0.441858 MMX, fees = 0 MMX** - What determines the size of the award?
5. **[Node] INFO: New peak at height 47146 with score 572** - My value must be less than this value (score) to create a block, right?
5. Is everything okay in this log?

**Comment by madMAx43v3r** [comment]
1. That's normal, some peer connection was lost.
2. Yeah it's fine, `took` should be less than `delta`.
3. It seems you have a low limit on maximum number of open files, it still works but you could increase it.
4. The variable reward function is as follows: reward = max(max(difficulty * const_factor, min_reward), TX fees). Where min_reward and const_factor are fixed at launch.
5. Must be less than 1000, lowest score wins (there are 7-8 candidates on average every 10 sec)
6. Apart from 3 yes.

**Comment by Kerby247** [comment]
Understood! Thanks!
Please tell me how to correctly increase the limit for the third point? Ubuntu runs on Windows.

**Comment by madMAx43v3r** [comment]
https://www.tecmint.com/increase-set-open-file-limits-in-linux/
