### ISSUE TITLE
Failed to create OpenCL GPU context: clGetDeviceIDs() failed

### ISSUE THREAD

**Issue by echoboss** [madMAx43v3r/mmx-node#124]
```shell 

[mmx_node] INFO: Failed to create OpenCL GPU context: clGetDeviceIDs() failed
[mmx_node] INFO: AVX2 support:   yes
[mmx_node] INFO: SHA-NI support: yes

✦ ❯ nvidia-smi -L
GPU 0: NVIDIA GeForce GTX 1650 (UUID: GPU-d7244b47-32a3-d23a-1815-0c257ab26fc2)

how to fix it？

**Comment by madMAx43v3r** [comment]
There's an issue on Windows Laptops which requires a config file config/local/opencl/platform with contents "NVIDIA CUDA" (including the quotes) to make it detect the GPU (opencl_device should be 0 in this case as well).

**Comment by echoboss** [comment]
> There's an issue on Windows Laptops which requires a config file config/local/opencl/platform with contents "NVIDIA CUDA" (including the quotes) to make it detect the GPU (opencl_device should be 0 in this case as well).

nice, it's working.
