### ISSUE TITLE
Can't locate other drive dirs

### ISSUE THREAD

**Issue by chinabala** [madMAx43v3r/mmx-node#13]
At instructed, when putting my plots location on plot_dirs Harvester.json
"/home/user/plots/", "/mnt/f/plots/"

/home dirs' working properly.
but, /mnt/f isn't.....

Anyone encounter the same issue?

**Comment by madMAx43v3r** [comment]
I think it's a permission problem

**Comment by xkredr** [comment]
If it is a permission thing the easiest way would be to `sudo chmod 777 -R /mnt`
This will set permissions for all mountpoints to rwx for user, group and everyone. Everyone can do everything on the mounted drives then.
