### ISSUE TITLE
Docker `edge` tags broken

### ISSUE THREAD

**Issue by felixbrucker** [madMAx43v3r/mmx-node#137]
https://github.com/madMAx43v3r/mmx-node/pull/133 broke docker edge tags, specifically this change: https://github.com/madMAx43v3r/mmx-node/pull/133/files#diff-3f5366f6d6df3ec1179e5efadc6f350bfa88eebf4e2da589b4d94ccb85ae5e94R54

Since, no new `edge` tags are pushed, as now only tags are pushed which is wrong

As now not only `master` will be built the condition needs to be fixed to include `master` pushes

**Comment by stotiks** [comment]
I will fix this

**Comment by stotiks** [comment]
#138

**Comment by felixbrucker** [comment]
Closed by https://github.com/madMAx43v3r/mmx-node/pull/138
