### ISSUE TITLE
Node does not recover

### ISSUE THREAD

**Issue by antcasq** [madMAx43v3r/mmx-node#148]
After start farming in testnet9 I notice that after a few minute I get out of sync with the blockchain.
The system/node must be restarted in order to start sync again...
``
==> 2022-12-12 21:10:54 [Node] WARN: Lost sync due to progress timeout!
==> 2022-12-12 21:10:54 [Node] INFO: Starting sync at height 43663
(...)
Never syncs again
``

[message.txt](https://github.com/madMAx43v3r/mmx-node/files/10212594/message.txt)

**Some notes about my environment:** 
Running MMX from Machinaris: https://github.com/guydavis/machinaris
It was working fine in testnet8

**Comment by madMAx43v3r** [comment]
From discord: could be an issue with AMD driver, because I dont see Verified VDF messages or warnings that it failed (during the time where sync was lost), but you still receiving them

**Comment by antcasq** [comment]
After compiling the code from github and running that native version instead of running MMX inside the container the problem did not happen again.
