### ISSUE TITLE
OpenCL install for i7-10700 (comet lake) on Ubuntu 20.04

### ISSUE THREAD

**Issue by xkredr** [madMAx43v3r/mmx-node#15]
Per the current install instructions the `clinfo `command would only give: `Number of Platforms     0`
Looks as if `sudo apt install intel-opencl-icd` may be a bit too cumbersome.

I found additional OpenCL installation instructions at [https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html]

Is the output of `clinfo` as expected now (see attachment please)? 
Is stopping and restarting the node sufficient to make use of the GPU? reboot? rebuild?
Should CPU load reduce significally when running with timelord (it does not yet....)

Thanks for any help;-)
[clinfo_output.txt](https://github.com/madMAx43v3r/mmx-node/files/7783869/clinfo_output.txt)

**Comment by madMAx43v3r** [comment]
> Should CPU load reduce significally when running with timelord (it does not yet....)

It should be half, when using OpenCL + timelord.

clinfo looks good, should be working. needs a node restart yes.

**Comment by xkredr** [comment]
Thanks. Wanted something lighter to keep running 24/7 for testnet so I set up a NUC7 with Pentium J5005 quad core with GPU (Gemini Lake).
Adding {user} to group render as well as video still didn't make OpenCL available (clinfo -> Number of Platforms 0).
Again the full set of instructions from [(https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html)] did, with the intel-opencl-icd package installed.  
Timelord is doing ~1.3 - 1.5 M/s Iterations.intel-opencl-icd

**Comment by gorenstein** [comment]
> sudo apt install intel-opencl-icd
prefer to use latest version from https://github.com/intel/compute-runtime
default intel-opencl-icd from Ubuntu repo have some problem on my PC

**Comment by xkredr** [comment]
thanks! I also had no success with intel-opencd-icd from ubuntu repo. Installing as in the instructions from [https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html](url) sets up an intel graphics repository. I think it was from that repo than I had more success getting OpenCL to work.
