### ISSUE TITLE
Video card stays in an unfavorable power state

### ISSUE THREAD

**Issue by maxpla3** [madMAx43v3r/mmx-node#156]
System: Ubuntu 20.04 LTS Desktop with RTX 3080Ti and 525.60.11 drivers.

Issue: As soon as the mmx node starts the video card switches from P8 to P2 power state, even at 0% load. The card is drawing 100W at 0% load and 130W when VDF verification is running. The card switches back to P8 power state after the mmx node is terminated. The card draws 25W in P8.
Why is it that the video card stays in P2 all the time when mmx node is running even though it is at 0% load most of the time? This leads to energy waste. Would it be possible to let the card only switch to P2 when there is actual work to be done?

**Comment by madMAx43v3r** [comment]
From what I know, whenever a CUDA or OpenCL application is running, the power state is fixed at P2.

**Comment by maxpla3** [comment]
> This is an issue, but it's outside of my control... the driver controls the power state. However you can set a fixed power state I believe, to limit power draw at the cost of higher VDF times.

That would be probably an effective workaround.

> From what I know, whenever a CUDA or OpenCL application is running, the power state is fixed at P2.

Would it be possible to design the VDF verification such that the OpenCL process starts only when there is a verification to do and ends immediately after the verification has finished?

**Comment by madMAx43v3r** [comment]
Yeah it's possible to create the OpenCL context only on demand. The question is still if that solves the issue, there may be a delay for going back to a lower power state...

**Comment by maxpla3** [comment]
I made a simple test to check how long the video card stays in an elevated power state after destroying the OpenCL context. After about one second the card switches from P2 to P5 and after another second to P8. This means that it will stay in the power saving state for 80% of the time (8 out of 10 seconds). 
Creating the OpenCL context on demand with would reduce the average power of a 3080Ti from 106W to 46W.

Your suggested workaround involving an enforced power state is working fine on my machine. I have to simply fix the memory clock to the lowest possivle value via `nvidia-smi -lmc 405` and the card stays in P8 at any time.

You can find available clocks for your nvidia card with `nvidia-smi -q -d SUPPORTED_CLOCKS | more`
