### ISSUE TITLE
Command 'mmx' not found

### ISSUE THREAD

**Issue by chinabala** [madMAx43v3r/mmx-node#2]
After installation, run mmx wallet create, and it says command not found.
Am I in wrong directory or missing something?

**Comment by onegoku** [comment]
try `. ./activate.sh` after you install everything

**Comment by chinabala** [comment]
> try `. ./activate.sh` after you install everything

thanks. I did use . ./activate.sh after install it. 
seems like node command would run, I saw it's syncing.
but under mmx-node directory, still can't find mmx command...

**Comment by madMAx43v3r** [comment]
The `mmx` binary is in `mmx-node/build/` folder. The `activate.sh` puts that folder in the `PATH` variable.

**Comment by chinabala** [comment]
thanks, once updated, everything works fine:)
