### ISSUE TITLE
Compile dies with Error 2

### ISSUE THREAD

**Issue by zhando** [madMAx43v3r/mmx-node#20]
Arch Linux
Ryzen 3400G

[ 36%] Building CXX object vnx-base/CMakeFiles/vnx_base.dir/src/JRPC_Response.cpp.o
[ 36%] Building CXX object vnx-base/CMakeFiles/vnx_base.dir/src/Stream.cpp.o
[ 36%] Building CXX object vnx-base/CMakeFiles/vnx_base.dir/src/Gateway.cpp.o
[ 36%] Building CXX object vnx-base/CMakeFiles/vnx_base.dir/src/RequestQueue.cpp.o
[ 37%] Linking CXX shared library libvnx_base.so
[ 37%] Built target vnx_base
make: *** [Makefile:136: all] Error 2

**Comment by curmudge0n** [comment]
Seeing the same thing w/ Arch on an A10-7700K.

[ 32%] Building CXX object vnx-base/CMakeFiles/vnx_base.dir/src/JRPC_Response.cpp.o
[ 32%] Building CXX object vnx-base/CMakeFiles/vnx_base.dir/src/Stream.cpp.o
[ 32%] Building CXX object vnx-base/CMakeFiles/vnx_base.dir/src/Gateway.cpp.o
[ 32%] Building CXX object vnx-base/CMakeFiles/vnx_base.dir/src/RequestQueue.cpp.o
[ 33%] Linking CXX shared library libvnx_base.so
[ 33%] Built target vnx_base
make: *** [Makefile:136: all] Error 2

**Comment by curmudge0n** [comment]
Installed `opencl-headers ` and it now compiles & runs.

**Comment by zhando** [comment]
That worked. Thanks!~
