### ISSUE TITLE
CMake Error when Building using ./make_devel.sh

### ISSUE THREAD

**Issue by holdings0012** [madMAx43v3r/mmx-node#21]
CMake Error at vnx-addons/CMakeLists.txt:11 (add_library):
  No SOURCES given to target: url_cpp

CMake Generate step failed.  Build files cannot be regenerated correctly.
make: *** No targets specified and no makefile found.  Stop.
What should I do? Cmake version is 3.16.3.

**Comment by madMAx43v3r** [comment]
You did this?
`git submodule update --init --recursive`

**Comment by holdings0012** [comment]
Not successed(something like TLS error). so i download submodule files manually. Nevermind , i think maybe i should stop trying something i am not familiar with。thanks

**Comment by holdings0012** [comment]
> You did this? `git submodule update --init --recursive`
