### ISSUE TITLE
Got invalid proof: invalid proof keys or port

### ISSUE THREAD

**Issue by anchoret2009** [madMAx43v3r/mmx-node#22]
When I run testnet1, I could get rewards almost 10MMX /hour.
But I run testnet3, I could not get any rewards for half day.

attached is the log snapshot.
![mmx_log](https://user-images.githubusercontent.com/1978961/148209980-79f19f69-774f-43bd-b539-5078bdac6e01.jpg)

**Comment by madMAx43v3r** [comment]
You need to re-plot with the new format, sorry about that. See readme, need latest `chia-plotter`.
The old plots were not really unique, that was a mistake on my part.

**Comment by anchoret2009** [comment]
thanks for your response. I begin to replot already. so far so good.
