### ISSUE TITLE
Core dumps on startup

### ISSUE THREAD

**Issue by zhando** [madMAx43v3r/mmx-node#23]
Arch Linux
Ryzen 3400G

./run_node.sh (fresh pull, testnet3) results in:

....
endpoint = ":11331"
mmx_node.log_file_level = 3
mmx_node.log_file_name = "mmx_node"
mmx_node.log_file_path = "testnet3/logs/"
parent = "../default/"
root_path = "testnet3/"
vnx.authentication.permissions.LOCALHOST = ["mmx.permission_e.PUBLIC", "mmx.permission_e.SPENDING", "CONST_REQUEST", "REQUEST"]
vnx.authentication.permissions.NETWORK = ["mmx.permission_e.PUBLIC"]
[mmx_node] INFO: Writing to log file: testnet3/logs/mmx_node_2022_01_05.txt
free(): invalid pointer
./run_node.sh: line 15: 153895 Aborted                 (core dumped) ./build/mmx_node -c config/${NETWORK}/ config/local/ $@

**Comment by madMAx43v3r** [comment]
Can you try a clean build:
```
./clean_all.sh
./update.sh
```

**Comment by zhando** [comment]
Still core dumps:

config = ["config/test3/", "config/local/"]
endpoint = ":11331"
mmx_node.log_file_level = 3
mmx_node.log_file_name = "mmx_node"
mmx_node.log_file_path = "testnet3/logs/"
parent = "../default/"
root_path = "testnet3/"
vnx.authentication.permissions.LOCALHOST = ["mmx.permission_e.PUBLIC", "mmx.permission_e.SPENDING", "CONST_REQUEST", "REQUEST"]
vnx.authentication.permissions.NETWORK = ["mmx.permission_e.PUBLIC"]
[mmx_node] INFO: Writing to log file: testnet3/logs/mmx_node_2022_01_05.txt
[mmx_node] INFO: No OpenCL GPU platform found: clGetDeviceIDs() failed
[Server] INFO: Running on localhost:11331
[Router] INFO: Loaded 4 known peers
[Router] INFO: Loaded 0 farmer credits
[HttpServer] INFO: Running on localhost:8080
[Router] INFO: Our Node ID: 32a8cd400fd0376777f3c40dbfdfa7956538b11afa70f8950aaf5f6f57a5369c
[HttpServer] INFO: Got component 'Node' for path '/api/node/'
[HttpServer] INFO: Got component 'Wallet' for path '/api/wallet/'
[Node] ERROR: clCreateProgramWithSource() failed with CL_INVALID_CONTEXT
terminate called without an active exception
./run_node.sh: line 15: 195131 Aborted                 (core dumped) ./build/mmx_node -c config/${NETWORK}/ config/local/ $@

Same processor (a Ryzen APU) worked with testnet 2.

**Comment by madMAx43v3r** [comment]
That's really strange... why would it try to build OpenCL kernels if no devices were detected...

**Comment by madMAx43v3r** [comment]
Ok was a bug, try again with `./update.sh`.

**Comment by zhando** [comment]
Still core dumps:
...
config = ["config/test3/", "config/local/"]
endpoint = ":11331"
mmx_node.log_file_level = 3
mmx_node.log_file_name = "mmx_node"
mmx_node.log_file_path = "tesI'tnet3/logs/"
parent = "../default/"
root_path = "testnet3/"
vnx.authentication.permissions.LOCALHOST = ["mmx.permission_e.PUBLIC", "mmx.permission_e.SPENDING", "CONST_REQUEST", "REQUEST"]
vnx.authentication.permissions.NETWORK = ["mmx.permission_e.PUBLIC"]
[mmx_node] INFO: Writing to log file: testnet3/logs/mmx_node_2022_01_06.txt
free(): invalid pointer
./run_node.sh: line 15: 92331 Aborted                 (core dumped) ./build/mmx_node -c config/${NETWORK}/ config/local/ $@

**Comment by zhando** [comment]
Ok I removed opencl-amd and opencl-amd-dev. Started from scratch and it worked. Thanks.
