### ISSUE TITLE
missing dependency libmmx_pos (cmake issue?)

### ISSUE THREAD

**Issue by tjb-altf4** [madMAx43v3r/mmx-node#238]
error while starting up mmx-node docker:
```
mmx_node: error while loading shared libraries: libmmx_pos.so: cannot open shared object file: No such file or directory
```
closest reference I can find is `mmx_pos` in cmake list, so maybe a typo somewhere? 
Or otherwise not being built correctly?

Seems to be impact others (linux) attempting to build from source also.

**Comment by madMAx43v3r** [comment]
I forgot to install it, should be fixed now

**Comment by tjb-altf4** [comment]
Thanks, I'm up and running now!

One last thing, could you rerun the Actions for docker tagged releases so they get updated e.g. `0.11.1-nvidia`
Only the "latest" docker tags were updated with your fixes e.g.  `edge-nvidia`
