### ISSUE TITLE
Got invalid proof: invalid proof keys or port

### ISSUE THREAD

**Issue by bogdanszmyd** [madMAx43v3r/mmx-node#26]
Everything worked fine but for several days mmx has not farmed and is showing the following message. I didn't change anything.

Node] INFO: -------------------------------------------------------------------------------
[Node] INFO: Verified VDF for height 73826, delta = 10.0318 sec, took 1.40688 sec
[Node] INFO: Finalized height 73818 with: ntx = 0, score = 1677, k = 32, tdiff = 32346, sdiff = 4611
[Node] INFO: New peak at height 73826 with score 16384, delay 1.40748 sec, took 0.003383 sec, 188 blocks
[Harvester] INFO: 14 plots were eligible for height 73835, best score was 16140, took 0.998277 sec
**[Node] WARN: Got invalid proof: invalid proof keys or port**
[Node] INFO: New peak at height 73826 with score 3811, forked at 73825, delay 5.04865 sec, took 0.02702 sec, 189 blocks
[HttpServer] INFO: 0 requests, 0 failed, 0 timeout, 0 sessions, errors=[]
[Router] INFO: 0 tx/s, 0.1 vdf/s, 0.65 proof/s, 0.1 block/s, 8 / 8 / 133 peers, 0 upload, 0 / 0 / 0 / 0 dropped
[Router] INFO: A majority of 7 / 8 peers agree at height 73819
[Node] INFO: -------------------------------------------------------------------------------
[Node] INFO: Verified VDF for height 73827, delta = 10.034 sec, took 1.36418 sec
[Node] INFO: Finalized height 73819 with: ntx = 0, score = 1666, k = 32, tdiff = 32315, sdiff = 4610
[Node] INFO: New peak at height 73827 with score 1124, delay 1.06085 sec, took 0.030477 sec, 189 blocks
[Harvester] INFO: 15 plots were eligible for height 73836, best score was 7832, took 0.999346 sec
**[Node] WARN: Got invalid proof: invalid proof keys or port**
[Router] INFO: A majority of 7 / 8 peers agree at height 73820
[Node] INFO: -------------------------------------------------------------------------------
[Node] INFO: Verified VDF for height 73828, delta = 10.004 sec, took 1.43326 sec
[Node] INFO: Finalized height 73820 with: ntx = 0, score = 2104, k = 30, tdiff = 32284, sdiff = 4611
[Node] INFO: New peak at height 73828 with score 1233, delay 1.05561 sec, took 0.031722 sec, 189 blocks
[Harvester] INFO: 12 plots were eligible for height 73837, best score was 11395, took 1.02281 sec
**[Node] WARN: Got invalid proof: invalid proof keys or port**
[Router] INFO: Peer 185.12.124.24 has insufficient credits to relay VDF for height 46340, verifying first.
[Router] INFO: A majority of 7 / 8 peers agree at height 73821

**Comment by madMAx43v3r** [comment]
Looks like you have old plots which are not compatible with testnet3?

**Comment by madMAx43v3r** [comment]
Or maybe added some chia plots by accicent?

**Comment by bogdanszmyd** [comment]
> Looks like you have old plots which are not compatible with testnet3?
Yes, they are for testnet2. How to go back to testnet2 ?
