### ISSUE TITLE
Remote harvester

### ISSUE THREAD

**Issue by chinabala** [madMAx43v3r/mmx-node#27]
I'm trying to run remote harvester for mmx, under WSL environments.

I ran this command on my main machine to get plots on remote harvester: 
`./run_harvester.sh -n 10.0.1.3:11330`

It seems alright that I connect to remote, but it says Connect Failed:
`vnx.authentication.permissions.NETWORK = ["mmx.permission_e.PUBLIC"]
vnx.authentication.permissions.USER = ["mmx.permission_e.PUBLIC", "PUBLISH"]
[Proxy] INFO: enable_export('harvester.info')
[Proxy] INFO: enable_export('harvester.proof')
[Proxy] INFO: enable_forward('Node', 100, 1000)
[Proxy] INFO: enable_forward('Farmer', 100, 1000)
[Server] INFO: Running on 0.0.0.0:11333
[Harvester] INFO: Loaded 177 plots, 4.11699 TiB total
[Proxy] WARN: connect() failed with: Resource temporarily unavailable (11) (10.0.1.3:11330)`

On the other hand, I've checked my node status and it seems it's succeed reading my plots?
`[Router] INFO: A majority of 4 / 4 peers agree at height 78353
[Node] INFO: -------------------------------------------------------------------------------
[Node] INFO: Verified VDF for height 78361, delta = 9.9194 sec, took 2.36062 sec
[Node] INFO: Finalized height 78353 with: ntx = 0, score = 2512, k = 32, tdiff = 32527, sdiff = 5113
[Node] INFO: New peak at height 78361 with score 1148, delay 0.529459 sec, took 0.113685 sec, 130 blocks
[Harvester] INFO: 2 plots were eligible for height 78370, best score was 35522, took 0.301945 sec
[TimeLord] INFO: 1.65143 M/s iterations`

By the way, I get this message on my node sometimes, do I need to worry?
`[Node] WARN: Got invalid proof: invalid proof keys or port`

Anyone encounter same issue here? Or any suggestion to fix it?

**Comment by madMAx43v3r** [comment]
`[Proxy] WARN: connect() failed with: Resource temporarily unavailable (11) (10.0.1.3:11330)`

Does this warning keep getting printed? If it's just once then no issue.

`[Node] WARN: Got invalid proof: invalid proof keys or port`

That means you have some incompatible plots, either chia plots or old MMX plots from testnet1/2

**Comment by chinabala** [comment]
I figured out. Your remote feature are running properly. 

run_harvester.sh should execute on remote machine, and IP should be the local/main machine.
I made mistake put them in opposite.
