### ISSUE TITLE
Running mmx-node on slow machine

### ISSUE THREAD

**Issue by chinabala** [madMAx43v3r/mmx-node#30]
Testing out mmx-node performance on slow machine. Out of luck....
It's a 4 core 2GHz CPU, with Intel HD graphic.

Tried this command as suggested, it's installed,
`sudo apt install beignet-opencl-icd`
But, I won't be able to enable iGPU where stocked in this command:
`sudo grub-mkconfig -o /boot/grub/grub.cfg`
it says: /usr/sbin/grub-probe: error: failed to get canonical path of `rootfs'.

So I tried other approach, to let my fast machine run farmer, timelord remotely to help the slow one.
1. I don't see major difference between ./run_farmer.sh and ./run_harvester.sh. They both work the same? As the screen prints out shows, it looks like harvester to me.. this doesn't help.
2. I ran ./run_timelord.sh on fast machine and seems slow machine picks up, but it still processing VDFs. So this won't work too.
3. I disable timelord on slow machine with command, but timelord is still running.
`./run_node.sh --timelord 0`
I tried to disable it on `echo false > config/local/timelord`, but I get permission denied.

All above won't work for me, so I turn it to remote harvester only. ( ./run_harvester.sh on slow machine, and ./run_node.sh on fast machine)
The obvious result is, I got zero MMX reward for 48 hours farming....
There were no WARN message at all, seems all working properly (I guess). However, I noticed that fast node machine got 0Tb plots, but slow harvester machine has 5Tb. This is normal as it should, right?)

I think we should set a minimum machine specification. Farming mmx requires more hardwares than chia.

**Comment by madMAx43v3r** [comment]
Timelord is optional, but VDFs still need to be verified (those are not the same thing). Latest version should show a summary of all connected remote harvesters. If it shows zero on your node then something is not right, probably the connection between harvester and node is not working (there should be warnings on the harvester).

**Comment by programkom** [comment]
Hi! I'm writing within this post, so i dont open new one... I also think there is something wrong with my node on same PC that i've been using for testnet 1 and 2...There i received some MMX rewards for 5TB plots, but on testnet4 and with all time updated client I seem to farm 0 MMX. I did re-plot everything (5TBs), so plots are not the cause. I also get VDF warnings (took 14+ sec), does this affect farming?

**Comment by madMAx43v3r** [comment]
> I also get VDF warnings (took 14+ sec)

Yes, it's that's consistent you won't be able to farm. Has to be less than 10 sec.

**Comment by programkom** [comment]
What can be done to remedy this? PC is not that bad, and testnet 1/2 was able to farm without problems...I also farm chia without any issues... I would assume that farming should not be so hard since plotting is hard enough :P

**Comment by madMAx43v3r** [comment]
Older testnets didn't have as fast timelords as now. Best way would be to add a small Nvidia GPU to the rig, like a GTX 650 or Quadro K620 / K2000.

**Comment by programkom** [comment]
Hmm, sadge :( my aim was to invest in HDDs and let them run on RaspberryPI (which is a nice feature of CHIA) or HP ELITEDESK 800 G2 MINI PC (which has INtel HD Graphics 530), since I have several of them. Keep in mind that low power consumption is a factor in these proof-of-space coins, so farming rig needs to use as less power as possible. This idea was working fine until now. I doubt I will add some HW just to farm MMX, maybe only option for me is to farm remotely from some faster PC/server and connect via VPN to HDD host rig.

**Comment by chinabala** [comment]
> Keep in mind that low power consumption is a factor in these proof-of-space coins, so farming rig needs to use as less power as possible.

I thought the same. Will wait until mmx finalized minimum hardware requirements to see the maximum invest in this great project.
Using vantage HW to farm mmx is quite impossible, especially farming both chia and mmx at the same time. R Pi 4 cores' way less than enough so don't bother... With CPU/GPU requirements, I think mmx coin price may have 160USD/per to mine.

**Comment by madMAx43v3r** [comment]
HD Graphics 530 should work

**Comment by programkom** [comment]
It seems that windows client/build by stotiks solved issue for me...running it, it automatically uses graphics card for VDF verification and i'm receiving rewards now, without any VDF warnings...
