### ISSUE TITLE
CPU cores at 100%

### ISSUE THREAD

**Issue by ghost** [madMAx43v3r/mmx-node#6]
CPU cores running at 100%. Does this mean my old i5 laptop doesn't support OpenCL or some other reason? This is with node synced and timelord disabled: did **echo false > config/local/timelord** then started node. I confirmed that **false** is in the file.

I installed all as per instructions.

Also can't find option to safely stop node.

Thanks for any help.

**Comment by madMAx43v3r** [comment]
Ctrl+C will safely stop. Can you show output of `clinfo`?

**Comment by madMAx43v3r** [comment]
It's possible if your i5 is quite old you might need this package:
`sudo apt install beignet-opencl-icd`

**Comment by clearfrost** [comment]
Thanks for replying.
I installed the extra package, updated to your latest commits, rebooted and ran clinfo:

> Number of platforms                               1
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 2.0 beignet 1.3
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short
  Platform Extensions function suffix             Intel
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)

  Platform Name                                   Intel Gen OCL Driver
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel Gen OCL Driver
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   
  clCreateContext(NULL, ...) [default]            No devices found in platform
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No devices found in platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1
>
I notice it says above: **no supported GPU found**
I think my i5 is 3rd gen, pretty old I suppose.
Thanks again.

**Comment by madMAx43v3r** [comment]
Can you post detailed CPU model info?

**Comment by trisen1** [comment]
I have same problem.

Ubuntu 20.04 on WSL 2 with CUda installed

I7-4790k with Geforce GTX970

Every 10 seconds when new block is found usage of the fully synced full note goes to 100 %

Number of platforms                               1
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 2.0 beignet 1.3
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short
  Platform Extensions function suffix             Intel
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)

  Platform Name                                   Intel Gen OCL Driver
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel Gen OCL Driver
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)
  clCreateContext(NULL, ...) [default]            No devices found in platform
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No devices found in platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1

**Comment by clearfrost** [comment]
CPU info using lscpu:
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              2
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           58
Model name:                      Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
Stepping:                        9
CPU MHz:                         1197.447
CPU max MHz:                     3300.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        5188.26
Virtualization:                  VT-x
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        512 KiB
L3 cache:                        3 MiB
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     KVM: Vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB f
                                 illing
Vulnerability Srbds:             Vulnerable: No microcode
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acp
                                 i mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bt
                                 s rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_
                                 cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_
                                 timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_sh
                                 adow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_
                                 clear flush_l1d

```

**Comment by madMAx43v3r** [comment]
yeah that's Ivy Bridge, `beignet-opencl-icd` should support that...

**Comment by madMAx43v3r** [comment]
> I have same problem.
> 
> Ubuntu 20.04 on WSL 2 with CUda installed
> 
> I7-4790k with Geforce GTX970.
> 
> I tried with integrated GPU enabled in BIOS and without - result is same.
> 
> Every 10 seconds when new block is found usage of the fully synced full note goes to 100 %
> 
> Number of platforms 1 Platform Name Intel Gen OCL Driver Platform Vendor Intel Platform Version OpenCL 2.0 beignet 1.3 Platform Profile FULL_PROFILE Platform Extensions cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short Platform Extensions function suffix Intel beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware (If you have multiple ICDs installed and OpenCL works, you can ignore this message)
> 
> Platform Name Intel Gen OCL Driver Number of devices 0
> 
> NULL platform behavior clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...) Intel Gen OCL Driver beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware (If you have multiple ICDs installed and OpenCL works, you can ignore this message) clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...) clCreateContext(NULL, ...) [default] No devices found in platform beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware (If you have multiple ICDs installed and OpenCL works, you can ignore this message) clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT) No devices found in platform clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU) No devices found in platform beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware (If you have multiple ICDs installed and OpenCL works, you can ignore this message) clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU) No devices found in platform clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR) No devices found in platform clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM) No devices found in platform beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware (If you have multiple ICDs installed and OpenCL works, you can ignore this message) clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL) No devices found in platform
> 
> ICD loader properties ICD loader Name OpenCL ICD Loader ICD loader Vendor OCL Icd free software ICD loader Version 2.2.11 ICD loader Profile OpenCL 2.1

WLS doesn't support OpenCL or CUDA _yet_, according to MS.

**Comment by clearfrost** [comment]
beignet-opencl-icd is installed.

Followed your readme instructions to check iGPU working. Ran `sudo lspci -v -s $(lspci | grep VGA | cut -d" " -f 1)` which returned required **Kernel driver in use: i915**.

Updated to latest from git and rebuilt. Working but still constant 100% CPU. Can't run it like that but please let me know if there's anything I can try.
Many thanks.

**Comment by madMAx43v3r** [comment]
Try latest version, which supports older OpenCL version now.

Also try this: `sudo adduser $USER video`

**Comment by clearfrost** [comment]
Adding `sudo adduser $USER render` from your latest readme did the trick for me, thanks.

**Comment by dfunked** [comment]
Noticed the same thing on a KVM VM, which makes sense really as it didn't have any kind of passed through GPU... I guess I'll have to play around with docker or run it on a separate machine instead.

**Comment by xiaosongPeng** [comment]
> Thanks for replying. I installed the extra package, updated to your latest commits, rebooted and ran clinfo:
> 
> ```
> Number of platforms                               1
>   Platform Name                                   Intel Gen OCL Driver
>   Platform Vendor                                 Intel
>   Platform Version                                OpenCL 2.0 beignet 1.3
>   Platform Profile                                FULL_PROFILE
>   Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short
>   Platform Extensions function suffix             Intel
> beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
> (If you have multiple ICDs installed and OpenCL works, you can ignore this message)
> 
>   Platform Name                                   Intel Gen OCL Driver
> Number of devices                                 0
> 
> NULL platform behavior
>   clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel Gen OCL Driver
> beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
> (If you have multiple ICDs installed and OpenCL works, you can ignore this message)
>   clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   
>   clCreateContext(NULL, ...) [default]            No devices found in platform
> beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
> (If you have multiple ICDs installed and OpenCL works, you can ignore this message)
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
> beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
> (If you have multiple ICDs installed and OpenCL works, you can ignore this message)
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
> beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
> (If you have multiple ICDs installed and OpenCL works, you can ignore this message)
>   clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No devices found in platform
> 
> ICD loader properties
>   ICD loader Name                                 OpenCL ICD Loader
>   ICD loader Vendor                               OCL Icd free software
>   ICD loader Version                              2.2.11
>   ICD loader Profile                              OpenCL 2.1
> ```
> 
> I notice it says above: **no supported GPU found** I think my i5 is 3rd gen, pretty old I suppose. Thanks again.

have this problems been resolved?  I  have the same question

**Comment by madMAx43v3r** [comment]
this is a general problem with opencl driver support, not much we can do about it. you might have installed the wrong package, that's all I can think of.

**Comment by xiaosongPeng** [comment]
Platform Name Intel Gen OCL Driver
Number of devices 0

for intel packge ,I have installed the two package
1、<Intel® CPU Runtime for OpenCL™ Applications 18.1 for Linux* OS (64bit only)>
2、beignet

so should I install the <Intel® SDK for OpenCL™ Applications for Ubuntu*>?



At 2022-08-23 23:40:52, "Max" ***@***.***> wrote:

this is a general problem with opencl driver support, not much we can do about it. you might have installed the wrong package, that's all I can think of.

**Comment by xiaosongPeng** [comment]
Platform Name Intel Gen OCL Driver
Number of devices 0

for intel packge ,I have installed the two package
1、<Intel® CPU Runtime for OpenCL™ Applications 18.1 for Linux* OS (64bit only)>
2、beignet

so should I install the <Intel® SDK for OpenCL™ Applications for Ubuntu*>?

**Comment by xiaosongPeng** [comment]
on my dell server, I have <Intel(R) Xeon(R) CPU E5-2609 v2 @ 2.50GH>CPUs
but clinfo does not show the  CPU device!

**Comment by xiaosongPeng** [comment]
Thanks for your help，I am a novice to OpenCL.
**Actually, my Dell server has two <Intel(R) Xeon(R) CPU E5-2609 v2 @ 2.50GH> CPUs,while I add a  NVIDIA GeForce RTX 3090 by PCIe slot to the system.**

**The clinfo does dectect two platforms:**
Number of platforms                               2

  Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 3.0 CUDA 11.7.101
  Platform Profile                                FULL_PROFILE

  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 2.0 beignet 1.3
  Platform Profile                                FULL_PROFILE

Platform Name                                   NVIDIA CUDA
Number of devices                                 1
Device Name                                     NVIDIA GeForce RTX 3090

Platform Name                                   Intel Gen OCL Driver
Number of devices                                 0

Now, for the **NVIDIA CUDA** platform, **GeForce RTX 3090** is listed as a device;
for the **Intel Gen OCL Driver**platform, no device is listed.

**Suppose there are 5 computing tasks  in order in my project(task1,task2,task3,task4,task5),
How can I schedule the task1,task3 and task4 on the cpu while task2 and task5 on the GPU with OpenCL?
(note: task2 and task5 are programmed as opencl kernels)**

thanks a lot for your kind advice!

**Comment by madMAx43v3r** [comment]
when you use OpenCL you have to select a device. in this case the 3090 would be the first device.
