### ISSUE TITLE
Windows Native Support/GUI Wallets

### ISSUE THREAD

**Issue by DirtyDoctorDan** [madMAx43v3r/mmx-node#7]
Will you add native support for Windows and a graphical wallet? I think this is a great thing for wider accessibility among people who don't want to/know how to use linux/command line stuff but still want to trade or farm.

Always good to see new coins popping up.

Edit: I realize in hindsight this probably isn't intended as a Q&A, my bad, you can close the issue if you want

**Comment by madMAx43v3r** [comment]
Yeah there will be a GUI for sure, it'll take some time to develop though.

**Comment by DogeMonsterDev** [comment]
Hi @madMAx43v3r, interesting project, I made a simple design for MMX GUI. [Figme Link](https://www.figma.com/file/cqcqWPrfqlDPHYNqBTvOSD/mmx-gui?node-id=0%3A1).

If you think it is useful, I can keep going and try to finish the design.

I have some frontend experience, If time permits, I can also try to implement it via Electron.

![Full Node](https://user-images.githubusercontent.com/95570352/147859302-b2a5e851-e39d-4d5c-83cd-aed405e1eec3.png)

**Comment by sengexyz** [comment]
@DogeMonsterDev  Wow, nice work buddy. Look forward to seeing this GUI released. @madMAx43v3r the backend is heavy enough, will you consider supporting the 3rd party GUI in the architecture/programming level?

**Comment by madMAx43v3r** [comment]
I have a built-in HTTP server with JSON API, it's not finished yet, but eventually that's what GUIs will and can use.

**Comment by sengexyz** [comment]
@madMAx43v3r Awesome, great to know.
