### ISSUE TITLE
MMX.Node-0.6.12-win64.zip

### ISSUE THREAD

**Issue by Drhicom** [madMAx43v3r/mmx-node#70]
When installing the latest pakage MMX.Node-0.6.12-win64.exe

![50c4cee1f51d42910af80a8ff6e2953d037f18db](https://user-images.githubusercontent.com/81637574/175107883-788309c3-689c-4726-91e6-d484d7e781b9.png)

When I installed the latest Microsoft Visual C++ Redistributable this resoles the issue. Is it possible to include these in the install package, so the latest package is there.

Thanks and keep up the great work.

 https://docs.microsoft.com/en-GB/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by Jacek-ghub** [comment]
Here is the link to CefSharp FAQ talking about how to include MS VS redistributables:
https://github.com/cefsharp/CefSharp/wiki/Frequently-asked-questions#6-how-do-i-include-the-visual-studio-c-201220132015-redistributables-with-my-application

Maybe it would be not that difficult to have it included with stotik's builds?

It looks like that this problem will hit those that install MMX node on a freshly installed Win boxes (what potentially most of Win installs will do).  So, it would be really cool to help those people out.

Also, here is a general info about that problem from stackoverflow - https://stackoverflow.com/questions/42365731/cefsharp-could-not-load-file-or-assembly-cefsharp-core-dll-or-one-of-its-dep

**Comment by stotiks** [comment]
working on it

**Comment by stotiks** [comment]
fixed in [v0.6.15](https://github.com/stotiks/mmx-node/releases/tag/v0.6.15)

**Comment by Jacek-ghub** [comment]
Confirming the fix.  I have uninstalled both MMX and 2015-2019 distributables, installed MMX again, and it run fine.  However, redistributables were not installed (looks like were statically linked - same end result, easier for the installer part). @Drhicom you can close this issue (once you test it as well).

**Comment by Drhicom** [comment]
By install latest Microsoft Visual C++ Redistributable latest supported downloads
https://docs.microsoft.com/en-GB/cpp/windows/latest-supported-vc-redist?view=msvc-170
This correct the issue.
