### ISSUE TITLE
Win 10, MMX node v0.6.12 - missing UI

### ISSUE THREAD

**Issue by Jacek-ghub** [madMAx43v3r/mmx-node#71]
Hi, I started the latest node on a box that I access via RDP.  I shut down that RDP window for about 30 minutes, and once I restarted RDP, the node UI is missing (not listed on Task bar, not accessible via Ctrl+Tab).  Although, it is still running, as it shows in Task Manager.

I tried to start another instance, but it came back with an error (already running), what is kind of expected.  Would it be possible to force that other process to be the active window, before / after exiting this error dialog?

I know that I can force quit the offending node, but if there is a way to revive that process that would be really great.  For Chia, the most bc / wallet db corruptions are happening on Chia exit, as they don't control the shutdown process properly, so maybe there is a way to avoid such forced shutdowns?

Here is the screenshot:
![image](https://user-images.githubusercontent.com/85920330/175187837-af6bbbc0-eae1-41cd-b090-cea8f5a66200.png)

**Comment by stotiks** [comment]
Is not visible in notification area too?

**Comment by Jacek-ghub** [comment]
It happened a second time right now.  You are right, it was in the notification area, and came back visible without any problems!

So, I assume that that error message is yours (you check on startup for the running instance), so maybe modify that error message to let people know to check notification area as well?

**Comment by stotiks** [comment]
Will be fixed in the next version. Window will restore on second instance launch.

**Comment by stotiks** [comment]
fixed in [v0.6.15](https://github.com/stotiks/mmx-node/releases/tag/v0.6.15)

**Comment by Jacek-ghub** [comment]
It looks like ...16 version may be broken - slow syncing - so I just shut down that box.  Maybe ..17 will fix syncing, and I will test it then.  Although, I am leaving another slow box to sync overnight, as maybe it will finish it.

**Comment by Jacek-ghub** [comment]
Testing with v0.6.18

I don't see it happening.  The UI doesn't go into the background.

Closing this issue.
