### ISSUE TITLE
Windows builds - show the current build version, and potentially indicate that an update is available

### ISSUE THREAD

**Issue by Jacek-ghub** [madMAx43v3r/mmx-node#74]
As in the title.  

Actually, one more thing.  Looking at MMX Node GUI Properties / Details, it would be nice if
1. the version there would also reflect build version
2. the copyright field included whatever trademark name is appropriate (MMX Node), as copyright just for copyright doesn't really tells much, rather suggests some low quality malware
3. Not sure what "Language Neutral" means :)

I think the same should apply for other binaries / dlls.  Currently mmx / mmx_node / etc. basically don't have anything set there at all.

**Comment by stotiks** [comment]
> I think the same should apply for other binaries / dlls. Currently mmx / mmx_node / etc. basically don't have anything set there at all.

done for binaries, MMX Node GUI update will come later
![image](https://user-images.githubusercontent.com/47013208/176775506-b1ad60ed-bd58-4e54-a7f2-d79e7e696f08.png)

**Comment by Drhicom** [comment]
In some newer versions I'm sure items can be added, Help and about etc. In version 29 maybe add check for update. See I gave you some room.

**Comment by Jacek-ghub** [comment]
> add check for update

Speaking of which.  Maybe in the UI version we could have a notification about a new update?

**Comment by Jacek-ghub** [comment]
v0.6.22
Almost there. :)

MM Node GUI - compare "Language" section to those from other binaries:
![image](https://user-images.githubusercontent.com/85920330/176816966-57c4769c-f948-469b-b9e4-26bb406c4562.png)

Also, for some reason tx_bench.exe feels orphaned:
![image](https://user-images.githubusercontent.com/85920330/176816937-cc808f21-15fe-407b-9dbf-90ddb64eafc0.png)

Great job!!

As those are minor, closing this ticket.
