### ISSUE TITLE
Better feedback in Win UI when db is still syncing

### ISSUE THREAD

**Issue by Jacek-ghub** [madMAx43v3r/mmx-node#75]
I have a couple of Win 10/11 boxes that I am using to run / test mmx.  Today, I:
1. updated one to v..17
2. deleted db folder
3. copied a fully synced block_chain.dat from the other box (running v..16)

I did it about 2 1/2 hours ago.  For all that time, the UI is pretty much dead.  Looking at the size of db folder, it is at ~300,000, where the other box is at 900,000 - implying 1/3 of the sync is done.  

On v..12, when the sync started, 100% of the CPU was taken by mmx_node, with v..17 only about 30-40%

Also, looking at my logs it mainly has entries like that:

```
2022-06-27 13:58:51 [Node] INFO: Height 221000 ...
2022-06-27 13:59:02 [HttpServer] INFO: 5900 requests, 5878 failed, 6 timeout, 0 sessions, errors=[[404, 1], [503, 5877]]2022-06-27 13:59:27 [Node] INFO: Height 222000 ...
2022-06-27 14:00:02 [HttpServer] INFO: 5942 requests, 5920 failed, 6 timeout, 0 sessions, errors=[[404, 1], [503, 5919]]2022-06-27 14:00:04 [Node] INFO: Height 223000 ...

```

Is it possible to add to Win UI some extra section that would let the user know what is going on, where in the process the node is?

Here is the UI
![image](https://user-images.githubusercontent.com/85920330/176036358-bd94643b-edd0-4496-9b7a-e4601c1c0b4b.png)

**Comment by Jacek-ghub** [comment]
It was suggested on Discord to restart UI.  I did that, and the node came back with the top portion providing sync feedback!  So, at least there are some work arounds.

**Comment by madMAx43v3r** [comment]
for now, during DB replay the GUI wont work...

**Comment by madMAx43v3r** [comment]
should be fixed now, for windows please wait for next release

**Comment by Jacek-ghub** [comment]
Tested v0.6.18

UI starting to work almost immediately.  Issue fixed.
