### ISSUE TITLE
Adding Plot Count On dashboard

### ISSUE THREAD

**Issue by Drhicom** [madMAx43v3r/mmx-node#85]
Please add the plot count to the dashboard as suggested by Defo on discord 

This would be very helpful to all users.

**Comment by madMAx43v3r** [comment]
There will be a dedicated Farmer page on the GUI.

**Comment by Drhicom** [comment]
Thats going to be great, thanks

**Comment by Jacek-ghub** [comment]
> There will be a dedicated Farmer page on the GUI.

Any rough estimate?

**Comment by limsandy** [comment]
Q4 2022

**Comment by madMAx43v3r** [comment]
Before that for sure.

**Comment by Jacek-ghub** [comment]
It would be really great to have it done before going to mainnet, as it will help newcomers.

**Comment by Drhicom** [comment]
Thank you sir,

**Comment by Drhicom** [comment]
Just saw the fix in v0.7.4, 

thanks
