### ISSUE TITLE
Adding finished Plots to Farmer after creation

### ISSUE THREAD

**Issue by Drhicom** [madMAx43v3r/mmx-node#86]
Good morning,

When creating plots it should add them to the farmer listing so when they complete creating, they start farming automatically.

**Comment by madMAx43v3r** [comment]
Right now this is done at the next reload interval, which is 1h by default. Is that good enough?

The GUI plotter is kinda decoupled from the Farmer, so it's not easy to add this feature...

**Comment by Drhicom** [comment]
keep up the good work, will have other options requests when they arise.
