### ISSUE TITLE
Disabling NFT plot creation - both UI and CLI

### ISSUE THREAD

**Issue by Jacek-ghub** [madMAx43v3r/mmx-node#87]
Currently (Win, v0.6.23), one can go to Plotting panel, and turn on "Create NFT plot" switch.  This will populate "Pool Contract Address" field, and will let the user create NFT plots.

Also, if that command line is copied in the shell, the mmx plotter, it will also start churning those NFT plots.

Maybe for time being, when NFT plots are not working on test net, the UI should gray out that "Create NFT plot" switch, and plotter should either abort or at least warn users that those are not yet supported?

**Comment by limsandy** [comment]
We don't currently have a Windows version. I think you've mistaken us for Stotiks' fork. Byeee.

**Comment by rhernaus** [comment]
The "Pool Contract Address" is not filled in automatically when 'Create NFT plot' switch is toggled. There is also no way to know what value to enter in that field as it has to be a valid plotnft. And at this moment it is not yet possible to create a plotnft on the MMX blockchain.
Furthermore a warning for farmers that are reading this. If you could create a plotnft on testnet and use it to create plots, then those plots will NOT be usable on mainnet!

**Comment by Jacek-ghub** [comment]
> The "Pool Contract Address" is not filled in automatically when 'Create NFT plot' switch is toggled.

I installed MMX on another Win box, and the field is empty there.  So, not sure where that value came from on the other box.

As I mentioned, I have not tried to plot NFT plots, as I read docs.  However, seeing that other post, I assume that I could run with it, of course producing useless plots.

Still, I think that switch should be grayed out for time being, and re-enabled when we switch to mainnet.

**Comment by madMAx43v3r** [comment]
> We don't currently have a Windows version. I think you've mistaken us for Stotiks' fork. Byeee.

Stotiks is not a fork, his Windows version is official. @stotiks up to you if want to disable the NFT option for now.

**Comment by stotiks** [comment]
Should be fixed
