### ISSUE TITLE
Great new project, some observations and questions

### ISSUE THREAD

**Issue by xkredr** [madMAx43v3r/mmx-node#9]
On a HP Microserver Gen8 (Celeron dual-core 2.3GHz) I could:

install on Ubuntu 20.04 from instructions without a problem
run the node as per instructions
create a wallet, got -p and -f keys from the wallet
generate some k.26 and k.30 plots on my separate plotter

observations:

cpu usage very high (~96-100%) - even with timelord disabled with `--timelord 0` option
lots of warning 'connecting to peer xx.xx.xx.xx failed (cause 110/111/113)
Would be nice if the `mmx node show peers` command gets available soon (status TODO)

frequently forking, most of the time getting back in sync within a couple of blocks
creating and broadcasting blocks
getting rewards in the wallet (`mmx wallet show`), but sometimes 'loosing' them a bit later!?!

questions:
Is the forking due to inadequate number or instability of peers
Is the forking to be expected on a highly taxed cpu?
Is the forking reason for creating a block within the fork and getting and loosing that reward when synced again?

Very excited about your new project Max, compliments for the work done and do enjoy the holidays/new year celebration;-)

**Comment by xkredr** [comment]
Installed  `sudo apt install beignet-opencl-icd` now and clinfo gives:

(guess the old celeron has no usable gpu)

```
rich@MMX:~$ clinfo
Number of platforms                               1
  Platform Name                                   Intel Gen OCL Driver
  Platform Vendor                                 Intel
  Platform Version                                OpenCL 2.0 beignet 1.3
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_khr_depth_images cl_khr_spir cl_khr_icd cl_intel_accelerator cl_intel_subgroups cl_intel_subgroups_short
  Platform Extensions function suffix             Intel
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)

  Platform Name                                   Intel Gen OCL Driver
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Intel Gen OCL Driver
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)
  clCreateContext(NULL, ...) [default]            No devices found in platform
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No devices found in platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1
```

**Comment by madMAx43v3r** [comment]
yeah, with that CPU and no GPU you wont be able to stay in sync, that's why you lose block rewards also.

**Comment by madMAx43v3r** [comment]
`mmx node peers` is now available

**Comment by xkredr** [comment]
Dusted off a Xeon E3 4C/8T. Runs way better, not a single warning on the node console;-)
CPU still goes to 100% periodically, guess thats the VDF calculations it's doing.
Also installed a Nvidia Quatro K2200, will try to set that up. Just hope I don't end up on the darkside.....

Great that `mmx node show peers` is available, will update asap and set up port forwarding. Always nice to know your neighbors
